# Generated by Django 6.0.3 on 2026-03-17 09:29

import django.db.models.deletion
import music.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_alter_artist_name'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to='artist.artist'),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(validators=[music.models.release_date_validator]),
        ),
    ]
