# Generated by Django 6.0.3 on 2026-03-13 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('debut_year', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='artist_pic/')),
            ],
        ),
    ]
