# Generated by Django 6.0.3 on 2026-03-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=100)),
                ('publication_date', models.DateField()),
                ('cover_image', models.ImageField(default='default_cover_image.jpg', upload_to='cover_image/')),
            ],
        ),
    ]
